feat: doicheck
DominicGBauer/information-retrieval pull request #14
Opened 2021-10-20 19:37 UTC by RSwallow987

# Pull Request
DOI API Integration 
## Scope
Added Doi check and changed execution a bit to fit in with DOI API 
## Work Done
Added doi check 
## Steps to Test
Run Main

2021-10-20 20:13 UTC, MBRGA requested changes

2021-10-20 20:13 UTC, MBRGA commented on main.py
> +        filename="%s.pdf" % article.doi
We might run into trouble trying to save files with a "/" in the name

2021-10-21 05:01 UTC, RSwallow987 commented on main.py
> +        filename="%s.pdf" % article.doi
Thanks Marc - I didn't think of that, will change it

2021-10-21 10:38 UTC, MBRGA approved these changes

2021-10-21 10:57 UTC, merged